GT-RIPL/Awesome-LLM-Robotics

- README.md
[VLN-BERT](https://arxiv.org/abs/2004.14973) is among one of the early endeavors of applying pretrained models to robotic tasks. It basically learns a CLIP-like model that compares navigation trajectories and instructions, then uses it to select the best trajectory to execute.
> Adding VLN-BERT

- README.md
ProgPrompt: Generating Situated Robot Task Plans using Large Language Models, accepted by ICRA 2023
> Add one paper in Reasoning: ProgPrompt

- README.md
"Chat with the Environment: Interactive Multimodal Perception using Large Language Models"
A multimodel perception model using LLM. Accepted in IROS 2023, Detroit – IEEE/RSJ International Conference on Intelligent Robots.
> Added "Matcha" paper (IROS 2023)

- README.md
* **LLM-Reward**: "Language to Rewards for Robotic Skill Synthesis", *arXiv, Jun 2023*. [[Paper](https://language-to-reward.github.io/assets/l2r.pdf)] [[Website](https://language-to-reward.github.io/)]
> add paper: Language to Rewards for Robotic Skill Synthesis

- README.md
**Gato**: "A Generalist Agent", TMLR, Nov 2022. [[Paper/PDF](https://openreview.net/pdf?id=1ikK0kHjvj)] [[Website](https://www.deepmind.com/publications/a-generalist-agent)]
**RoboCat**: "RoboCat: A self-improving robotic agent", arxiv, Jun 2023. [[Paper/PDF](https://arxiv.org/abs/2306.11706)] [[Website](https://www.deepmind.com/blog/robocat-a-self-improving-robotic-agent)]
RoboCat is based on multimodal model Gato.
> Add paper: Gato and RoboCat

- README.md
Correct the link of paper "Keep CALM and Explore: Language Models for Action Generation in Text-based Games".
> Correct one paper's link.

- README.md
Add CortexBench paper and Implementation for Generative Agents. CLOSES #26
> Add CortexBench paper and Implementation for Generative Agents Closes #26

- README.md
- Add PhysObjects paper
- Add MetaMorph paper
> Add PhysObject and MetaMorph paper

- README.md
add one paper "Text2Reward: Automated Dense Reward Function Generation for Reinforcement Learning"
> add text2reward

- README.md
SPRINT: LLMs + offline RL for agent pretraining
BOSS: LLMs + online RL for learning new skills in new environments
> Adding SPRINT and BOSS papers to manipulation

- README.md
NLMap's original date is wrong (see arxiv info)
The project also features both navigation and manipulation
> Fix NLMap date in README

- README.md
Hello, nice work for LLM-robotics research! Just want to add two related papers: LEO, an LLM-based embodied generalist agent capable of handling various vision-language and robotics tasks in 3D scenes; and ARNOLD, a robotic simulation environment with a systematic benchmark for language-conditioned manipulation.
> Add LEO and ARNOLD

- README.md
Add two papers: grasp_anything and alphablock
> grasp_anything and alphablock

- README.md
Heuristic Planning with LLMs paper
> Added SayCanPay, AAAI 2024

- README.md
This pull request is about adding our recent arxiv paper Attentive Support to the repositoriy's planning section, and to update the recently added Co-Pal paper (accepted for ICRA). Thanks for your consideration!
> Add Attentive Support paper

- README.md
This commit adds the MoMa-LLM paper, which describes multi-room mobile manipulation from language prompts based on scene graphs. MoMa-LLM enables robotic navigation, exploration, and articulated object manipulation, which is demonstrated on the task of interactive object search.
> adds moma-llm paper

- README.md
Hi,  we update two LLM-robotics papers. 
The first one is to evaluate LLM-based autonomous driving safety and security performance, which has been accepted by IEEE IV24.
The other one is about implement LLM with mobile robots to do specific coverage path planning in our simulator.
Cheers.
> Add two related papers

- README.md
Add IROS paper for LLM planning, LLM3: Large Language Model-based Task and Motion Planning with Motion Failure Reasoning
> Add IROS paper for LLM planning

- README.md
Thank you! Updated according to chronological order in the second commit.
> adding new paper to LLM planning section

- README.md
Plan-Seq-Learn uses LLMs to guide RL for solving long-horizon RL tasks - added to Manipulation section.
> Add PSL Paper to Manipulation Section

- README.md
Added 3 papers to the list, all focusing on safety, risks, and functionality concerns regarding the deployment of LLMs and VLMs in robotics. The papers cover topics like discrimination, violence, and unlawful actions and red teamed prompting that LLM-driven robots could potentially enact, as well as highlighting broader safety concerns.
> Update README.md, add 3 papers on safety and risks of LLM-powered robots

- README.md
This paper uses an LLM to guide the exploration of an RL agent within the context of robot manipulation.
> Add ExploRLLM paper

- README.md
update paper link with published version
> update BTGenBot paper

- README.md
We’d love for you to add our paper to this repo. If you agree to our PR, we’d be so grateful!
> Add an adversarial attack paper on VLA models

- README.md
"This PR adds a new paper published in Nature Machine Intelligence titled 'Embodied large language models enable robots to complete long-horizon tasks in unpredictable settings' (March 2025)."
> Add ELLMER (Nature Machine Intelligence, 2025) to Reasoning section

- README.md
Add our paper of "LLM+MAP: Bimanual Robot Task Planning using Large Language Models and Planning Domain Definition Language"
> Add LLM+MAP

- README.md
Wanted to add a few relevant papers:
- [SPINE](https://zacravichandran.github.io/SPINE/): LLM-enabled reasoning and planning in partially-known and unstructured environments
- [RoboPAIR:](https://robopair.org/) red teaming LLM-enabled robots
- [RoboGuard](https://robo-guard.github.io/): safeguards for LLM-enabled robots.
> Add papers: SPINE / RoboPAIR / RoboGuard

- README.md
Hi, thanks for the great collection!
I want to add/update 2 of my papers:
Add:
- [RoboSpatial](https://chanh.ee/RoboSpatial/), CVPR 2025 Oral: A large-scale 2D/3D dataset of real indoor/tabletop environments for spatial reasoning in robotics.
Update conference info:
- [LLM-Planner](https://osu-nlp-group.github.io/LLM-Planner/): arxiv -> ICCV
Luke
> Adding RoboSpatial and updating LLM-Planner

- README.md
Hello! We would like to request the inclusion of our paper, **"RoboRefer: Towards Spatial Referring with Reasoning in Vision-Language Models for Robotics"**, into your awesome list.
Our contributions include:
- **🤖 A 3D Spatial Reasoning Model:** We propose **RoboRefer**, a 3D-aware reasoning VLM trained using a sequential SFT-RFT strategy with metric-sensitive process reward functions to achieve spatial referring.
- **📚 A Large-Scale Open-Source Dataset (RefSpatial):** To support this research, we have released the **RefSpatial** dataset, a large-scale collection of 2.5 million samples with 20 million QA pairs. It features fine-grained annotations for 31 distinct spatial relations. A key feature of our simulated data is the inclusion of detailed, step-by-step reasoning processes that …
> Update README.md: Add RoboRefer, a 3D spatial reasoning model with advanced dataset & benchmark
